### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by jniltinho**
Add support for FFMPEG 3.2

### CODE REVIEW

**Comment by jniltinho** [comment]
Add Support FFMPEG 3.2 + Install unzip

**Comment by strycore** [comment]
Please state what this pull request is about, your commit messages are absolutely non descriptive.

**Comment by strycore** [comment]
The pull request changes the URL of the git repo in the README, it won't be merged.

**Comment by jniltinho** [comment]
Add support for FFMPEG 3.2 in build.sh

ffmpeg_version="3.2"

**Comment by jniltinho** [comment]
Add unzip in install echo "Installing dependencies"

sudo apt-get -y --force-yes install **unzip** autoconf automake build-essential .....

**Comment by jniltinho** [comment]
Add support for SDK 7.0.1 in Gituhb
https://github.com/jniltinho/ffmpeg-nvenc

**Pull request closed without merging**
